# Generated by Django 5.1.15 on 2026-08-29 06:08

import billing.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, default=billing.models.generate_invoice_number, help_text='Unique auto-generated invoice identifier.', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice total amount.', max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20)),
                ('issued_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment terms, wire details, or client notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='Historical job associated with this invoice cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='jobs.job')),
            ],
            options={
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
    ]
